class_name DemoCatalog

const REPO_BASE_URL := "https://github.com/papercraftgames/fpe-rush/blob/main"

const DEMOS: Array[Dictionary] = [
	{
		"id": "01_scene_settings",
		"number": "01",
		"title": "Paper Morning",
		"concept": "Scene settings",
		"blurb": "Sky color and gravity arrive from Blender scene metadata.",
		"explanation": "This demo shows scene-level FPE metadata. Blender exports the scene context extras with sky color, gravity, and scene-load events; the Godot runtime reads those extras when the GLB loads and applies them to the active world instead of requiring a custom setup script.",
		"try_it": "Close the gallery, move and jump with the paper player, then compare this scene's warm sky and heavier gravity against later demos.",
		"play_hint": "Move with WASD or arrows; jump with Space",
		"accent": Color("#ef9a8f"),
		"event": "ActivateDemo",
		"metadata": "fpe_scene_context_props",
		"repo_path": "demos/glb/01_scene_settings.glb",
	},
	{
		"id": "02_groups",
		"number": "02",
		"title": "Ribbon Clubs",
		"concept": "Groups",
		"blurb": "Objects join Godot groups from a comma-separated FPE property.",
		"explanation": "This demo shows object grouping. The ribbon objects are tagged in Blender with FPE object extras that name their Godot groups. When FPE imports the GLB, it adds those nodes to the requested groups, so a later command can target the group instead of hard-coded node paths.",
		"try_it": "Walk to the raised paper button and press E to make the tagged ribbon group disappear.",
		"play_hint": "Approach the paper button and press E",
		"accent": Color("#e7b66d"),
		"event": "ActivateDemo",
		"metadata": "Groups: warm_ribbons, collectibles",
		"repo_path": "demos/glb/02_groups.glb",
	},
	{
		"id": "03_triggers",
		"number": "03",
		"title": "Welcome Mat",
		"concept": "Triggers",
		"blurb": "A tagged volume turns overlap or interaction into a named event.",
		"explanation": "This demo shows FPE trigger metadata. The welcome mat is authored as trigger geometry in Blender, with trigger groups and an event name stored in GLB extras. FPE upgrades that mesh into a trigger volume and dispatches the configured event when the player overlaps it.",
		"try_it": "Close the gallery and walk the player onto the translucent welcome mat, or press Activate to fire the same event.",
		"play_hint": "Walk onto the welcome mat",
		"accent": Color("#d9cb72"),
		"event": "ActivateDemo",
		"metadata": "fpe_trigger_events_context_props",
		"repo_path": "demos/glb/03_triggers.glb",
	},
	{
		"id": "04_event_commands",
		"number": "04",
		"title": "Postcard Route",
		"concept": "Event commands",
		"blurb": "A declarative event routes one moment into multiple commands.",
		"explanation": "This demo shows FPE's scene event command catalog. Blender exports one ActivateDemo event whose commands activate a camera, trigger a speaker, and dispatch a follow-up event. Godot only dispatches the event; FPE performs the configured actions from the GLB extras.",
		"try_it": "Walk to the paper button and press E: one event switches camera, rings the bell, and dispatches a follow-up event.",
		"play_hint": "Approach the paper button and press E",
		"accent": Color("#9fc58e"),
		"event": "ActivateDemo",
		"metadata": "SceneEvents[].Commands",
		"repo_path": "demos/glb/04_event_commands.glb",
	},
	{
		"id": "05_animations",
		"number": "05",
		"title": "Wind-Up Bloom",
		"concept": "Animations",
		"blurb": "FPE plays a Blender-authored action by its exported name.",
		"explanation": "This demo shows animation commands. The bloom movement is keyed in Blender and exported as the Bloom action. The FPE scene event references that action by name, so Godot can request the event while FPE finds and plays the authored animation.",
		"try_it": "Walk to the paper button and press E to play the Bloom action exported from Blender.",
		"play_hint": "Approach the paper button and press E",
		"accent": Color("#79b9a6"),
		"event": "ActivateDemo",
		"metadata": "Animations: Bloom",
		"repo_path": "demos/glb/05_animations.glb",
	},
	{
		"id": "06_cameras",
		"number": "06",
		"title": "Teacup Close-Up",
		"concept": "Cameras",
		"blurb": "Named Blender cameras become event-addressable viewpoints.",
		"explanation": "This demo shows authored camera handoff. The detail camera is placed and named in Blender, exported in the GLB, and referenced by an FPE ActivateCamera command. FPE registers the camera during load and switches to it when the event runs.",
		"try_it": "Walk to the paper button and press E to cut from the player camera to the authored teacup close-up.",
		"play_hint": "Approach the paper button and press E",
		"accent": Color("#71b8c8"),
		"event": "ActivateDemo",
		"metadata": "ActivateCamera: DetailCamera",
		"repo_path": "demos/glb/06_cameras.glb",
	},
	{
		"id": "07_speakers",
		"number": "07",
		"title": "Tiny Chime",
		"concept": "Speakers",
		"blurb": "Tagged geometry becomes a spatial audio speaker.",
		"explanation": "This demo shows speaker metadata. Blender marks the chime object as an FPE speaker and stores the audio file, volume, distance, and autoplay settings in extras. FPE turns that node into a spatial speaker and triggers it from the event command.",
		"try_it": "With audio enabled, walk to the paper button and press E to ring the spatial chime.",
		"play_hint": "Approach the paper button and press E to ring",
		"accent": Color("#83a8d8"),
		"event": "ActivateDemo",
		"metadata": "fpe_speaker_settings_context_props",
		"repo_path": "demos/glb/07_speakers.glb",
	},
	{
		"id": "08_rigid_physics",
		"number": "08",
		"title": "Tumble Parcel",
		"concept": "Rigid physics",
		"blurb": "Naming and physics metadata produce an enhanced rigid body.",
		"explanation": "This demo shows FPE rigid-body enhancement. The parcel is authored as a rigid object with physics extras such as mass and gravity scale. FPE recognizes the object during import and wires it into Godot physics without hand-building the body in the scene.",
		"try_it": "Close the gallery and bump the parcel with the player to feel the FPE-enhanced rigid body.",
		"play_hint": "Move into the parcel and keep it inside the rails",
		"accent": Color("#a69bd6"),
		"event": "ActivateDemo",
		"metadata": "Parcel-rigid + Physics",
		"repo_path": "demos/glb/08_rigid_physics.glb",
	},
	{
		"id": "09_holdables",
		"number": "09",
		"title": "Carry The Star",
		"concept": "Holdables",
		"blurb": "A rigid object opts into FPE's player hold zone.",
		"explanation": "This demo shows holdable object metadata. The star is a rigid object with FPE's Holdable flag. The player is also exported with hold-zone settings, so FPE gives the player a hold area and lets the tagged star be picked up through standard player input.",
		"try_it": "Walk to the star and press E or left click to pick up the holdable object. Press R to drop it.",
		"play_hint": "E or click: pick up; R: drop",
		"accent": Color("#c197cf"),
		"event": "ActivateDemo",
		"metadata": "Holdable: true",
		"repo_path": "demos/glb/09_holdables.glb",
	},
	{
		"id": "10_inventory",
		"number": "10",
		"title": "Keepsake Pocket",
		"concept": "Inventory",
		"blurb": "Pickup metadata declares an item kind and quantity.",
		"explanation": "This demo shows inventory pickup metadata. The keepsake is both holdable and tagged with an FPE inventory item kind plus quantity. FPE uses that metadata with the registered inventory config so the player can collect the item without bespoke pickup code.",
		"try_it": "Press E or left click on the keepsake: the item kind and quantity come from FPE inventory metadata.",
		"play_hint": "Approach the keepsake and press E",
		"accent": Color("#d593b7"),
		"event": "ActivateDemo",
		"metadata": "InventoryItemKind + Quantity",
		"repo_path": "demos/glb/10_inventory.glb",
	},
	{
		"id": "11_sub_scenes",
		"number": "11",
		"title": "Secret Nook",
		"concept": "Sub-scenes",
		"blurb": "A scene host can be loaded and unloaded through event commands.",
		"explanation": "This demo shows sub-scene hosting. Blender marks a host object with FPE sub-scene extras pointing at another GLB. The ActivateDemo event runs LoadSubScene, and FPE loads the authored nook into that host at runtime.",
		"try_it": "Walk to the paper button and press E to load the secret nook GLB into its host.",
		"play_hint": "Approach the paper button and press E",
		"accent": Color("#e38e9d"),
		"event": "ActivateDemo",
		"metadata": "LoadSubScene: SecretNook",
		"repo_path": "demos/glb/11_sub_scenes.glb",
	},
	{
		"id": "12_conversations",
		"number": "12",
		"title": "Neighbor Note",
		"concept": "Conversations",
		"blurb": "A command starts a resource-backed branching conversation.",
		"explanation": "This demo shows conversation commands. The note can dispatch ActivateDemo, and the FPE scene event starts a Godot conversation resource. The GLB owns the trigger/event wiring while the conversation text stays in a normal project resource.",
		"try_it": "Walk to the note or press Activate to start the conversation resource and show its first line.",
		"play_hint": "Approach the note and press E",
		"accent": Color("#e79f84"),
		"event": "ActivateDemo",
		"metadata": "StartConversation: neighbor_note.tres",
		"repo_path": "demos/glb/12_conversations.glb",
	},
	{
		"id": "13_water",
		"number": "13",
		"title": "Puddle Shine",
		"concept": "Water effect",
		"blurb": "One object flag applies FPE's animated water material.",
		"explanation": "This demo shows an FPE material/effect flag. The puddle mesh is tagged as Water in Blender. When FPE imports the GLB, it replaces that surface with the engine's water effect instead of requiring scene-specific material setup.",
		"try_it": "Close the gallery and walk around the puddle to inspect the animated FPE water material from several angles.",
		"play_hint": "Walk around the puddle to inspect the shader",
		"accent": Color("#73b7c7"),
		"event": "ActivateDemo",
		"metadata": "Water: true",
		"repo_path": "demos/glb/13_water.glb",
	},
	{
		"id": "14_ui_elements",
		"number": "14",
		"title": "Paper Buttons",
		"concept": "3D UI elements",
		"blurb": "Tagged meshes become camera-aware selectable controls.",
		"explanation": "This demo shows 3D UI element metadata. The paper button is exported with FPE UIElement extras and an interaction event. FPE upgrades the tagged mesh into a selectable 3D UI option so the scene can treat authored geometry as interface.",
		"try_it": "Move the player focus to the authored 3D paper button and use it to dispatch its event.",
		"play_hint": "Focus the 3D paper button and press E",
		"accent": Color("#89bd9a"),
		"event": "ActivateDemo",
		"metadata": "UIElement + UIOptions",
		"repo_path": "demos/glb/14_ui_elements.glb",
	},
	{
		"id": "15_frame_events",
		"number": "15",
		"title": "Clockwork Spark",
		"concept": "Frame events",
		"blurb": "Animation time can dispatch gameplay at an exact authored frame.",
		"explanation": "This demo shows animation frame events. The spark action is keyed in Blender and includes FPE frame-event extras. FPE plays the action and dispatches the configured event at the authored frame, keeping gameplay timing tied to animation data.",
		"try_it": "Walk to the paper button and press E, then watch the spark dispatch its event mid-animation.",
		"play_hint": "Approach the paper button and press E",
		"accent": Color("#e0bd68"),
		"event": "ActivateDemo",
		"metadata": "fpe_frame_event_context_props",
		"repo_path": "demos/glb/15_frame_events.glb",
	},
	{
		"id": "16_physical_puzzle",
		"number": "16",
		"title": "Garden Gate",
		"concept": "Physical puzzle",
		"blurb": "A trigger plays an animation that moves visible geometry and collision together.",
		"explanation": "This demo combines several FPE pieces into one small puzzle. Blender authors the player trigger, speaker, animated gate, and event command. FPE loads the metadata, listens for the trigger or ActivateDemo event, plays the gate animation, triggers audio, and dispatches the unlock event.",
		"try_it": "Walk the player to the gate bell or press Activate to open the path with an FPE animation command.",
		"play_hint": "Approach the gate bell and press E",
		"accent": Color("#ef856f"),
		"event": "ActivateDemo",
		"metadata": "Trigger -> Animations: GateOpen",
		"repo_path": "demos/glb/16_physical_puzzle.glb",
	},
]

static func glb_path(demo: Dictionary) -> String:
	return "res://demos/glb/%s.glb" % demo.id

static func repo_url(demo: Dictionary) -> String:
	return "%s/%s" % [REPO_BASE_URL, demo.repo_path]
