class_name DemoCatalog

const DEMOS: Array[Dictionary] = [
	{"id": "01_scene_settings", "number": "01", "title": "Paper Morning", "concept": "Scene settings", "blurb": "Sky color and gravity arrive from Blender scene metadata.", "try_it": "Load it, then compare the warm sky and heavier paper-world gravity against later scenes.", "accent": Color("#ef9a8f"), "event": "ActivateDemo", "metadata": "fpe_scene_context_props"},
	{"id": "02_groups", "number": "02", "title": "Ribbon Clubs", "concept": "Groups", "blurb": "Objects join Godot groups from a comma-separated FPE property.", "try_it": "Press Activate and watch the ribbon group disappear as FPE runs a group-targeted command.", "accent": Color("#e7b66d"), "event": "ActivateDemo", "metadata": "Groups: warm_ribbons, collectibles"},
	{"id": "03_triggers", "number": "03", "title": "Welcome Mat", "concept": "Triggers", "blurb": "A tagged volume turns overlap or interaction into a named event.", "try_it": "Close the gallery and walk the player onto the translucent welcome mat, or press Activate to fire the same event.", "accent": Color("#d9cb72"), "event": "ActivateDemo", "metadata": "fpe_trigger_events_context_props"},
	{"id": "04_event_commands", "number": "04", "title": "Postcard Route", "concept": "Event commands", "blurb": "A declarative event routes one moment into multiple commands.", "try_it": "Press Activate once: the event switches camera, rings the bell, and dispatches a follow-up route event.", "accent": Color("#9fc58e"), "event": "ActivateDemo", "metadata": "SceneEvents[].Commands"},
	{"id": "05_animations", "number": "05", "title": "Wind-Up Bloom", "concept": "Animations", "blurb": "FPE plays a Blender-authored action by its exported name.", "try_it": "Press Activate to play the Bloom action exported from Blender animation data.", "accent": Color("#79b9a6"), "event": "ActivateDemo", "metadata": "Animations: Bloom"},
	{"id": "06_cameras", "number": "06", "title": "Teacup Close-Up", "concept": "Cameras", "blurb": "Named Blender cameras become event-addressable viewpoints.", "try_it": "Press Activate to cut from the overview camera to the authored teacup detail camera.", "accent": Color("#71b8c8"), "event": "ActivateDemo", "metadata": "ActivateCamera: DetailCamera"},
	{"id": "07_speakers", "number": "07", "title": "Tiny Chime", "concept": "Speakers", "blurb": "Tagged geometry becomes a spatial audio speaker.", "try_it": "Press Activate with audio enabled to trigger the speaker node created from GLB extras.", "accent": Color("#83a8d8"), "event": "ActivateDemo", "metadata": "fpe_speaker_settings_context_props"},
	{"id": "08_rigid_physics", "number": "08", "title": "Tumble Parcel", "concept": "Rigid physics", "blurb": "Naming and physics metadata produce an enhanced rigid body.", "try_it": "Close the gallery and bump the parcel with the player to feel the FPE-enhanced rigid body.", "accent": Color("#a69bd6"), "event": "ActivateDemo", "metadata": "Parcel-rigid + Physics"},
	{"id": "09_holdables", "number": "09", "title": "Carry The Star", "concept": "Holdables", "blurb": "A rigid object opts into FPE's player hold zone.", "try_it": "Walk to the star and press E or left click to pick up the holdable object. Press R to drop it.", "accent": Color("#c197cf"), "event": "ActivateDemo", "metadata": "Holdable: true"},
	{"id": "10_inventory", "number": "10", "title": "Keepsake Pocket", "concept": "Inventory", "blurb": "Pickup metadata declares an item kind and quantity.", "try_it": "Press E or left click on the keepsake: the item kind and quantity come from FPE inventory metadata.", "accent": Color("#d593b7"), "event": "ActivateDemo", "metadata": "InventoryItemKind + Quantity"},
	{"id": "11_sub_scenes", "number": "11", "title": "Secret Nook", "concept": "Sub-scenes", "blurb": "A scene host can be loaded and unloaded through event commands.", "try_it": "Press Activate to load the secret nook GLB into the host object.", "accent": Color("#e38e9d"), "event": "ActivateDemo", "metadata": "LoadSubScene: SecretNook"},
	{"id": "12_conversations", "number": "12", "title": "Neighbor Note", "concept": "Conversations", "blurb": "A command starts a resource-backed branching conversation.", "try_it": "Walk to the note or press Activate to start the conversation resource and show its first line.", "accent": Color("#e79f84"), "event": "ActivateDemo", "metadata": "StartConversation: neighbor_note.tres"},
	{"id": "13_water", "number": "13", "title": "Puddle Shine", "concept": "Water effect", "blurb": "One object flag applies FPE's animated water material.", "try_it": "Load the scene and inspect the puddle surface; FPE swaps the tagged mesh to its water effect.", "accent": Color("#73b7c7"), "event": "ActivateDemo", "metadata": "Water: true"},
	{"id": "14_ui_elements", "number": "14", "title": "Paper Buttons", "concept": "3D UI elements", "blurb": "Tagged meshes become camera-aware selectable controls.", "try_it": "Use the 3D cursor/player focus on the paper button, or press Activate to dispatch its button event.", "accent": Color("#89bd9a"), "event": "ActivateDemo", "metadata": "UIElement + UIOptions"},
	{"id": "15_frame_events", "number": "15", "title": "Clockwork Spark", "concept": "Frame events", "blurb": "Animation time can dispatch gameplay at an exact authored frame.", "try_it": "Press Activate and watch the spark animation; the frame event fires mid-action.", "accent": Color("#e0bd68"), "event": "ActivateDemo", "metadata": "fpe_frame_event_context_props"},
	{"id": "16_physical_puzzle", "number": "16", "title": "Garden Gate", "concept": "Physical puzzle", "blurb": "A trigger plays an animation that moves visible geometry and collision together.", "try_it": "Walk the player to the gate bell or press Activate to open the path with an FPE animation command.", "accent": Color("#ef856f"), "event": "ActivateDemo", "metadata": "Trigger -> Animations: GateOpen"},
]

static func glb_path(demo: Dictionary) -> String:
	return "res://demos/glb/%s.glb" % demo.id
